### ISSUE TITLE
"no project dependency information found"

### ISSUE THREAD

**Issue by roy-ackermann** [mwalter/MavenDependencyChecker#6]
Intelij version: 2023.3.3
Plugin version: 1.10.0

When i run the dependency check, the plugin cannot read the dependency information. The message is "no project dependency information found".

The plugin still worked a while ago.

**Comment by mwalter** [comment]
Hi Roy, maybe you're behind a firewall?

**Comment by jack-geronimo** [comment]
I have the same problem in one project, in the other it works like a charm.
Unfortunately, I was unable to resolve the issue by running mvn clean and package again.

**Comment by mwalter** [comment]
Hi guys, thanks a lot for sharing your issues with the plugin.
I'm happy you could fix the problem, @Michaelafuller!

I'm not quite sure but the problem seems to occur in multi module Maven projects only. I created a multi module project for testing purpose but the issue didn't show up.

Are you using a Maven parent POM module in your projects which is referenced from other modules? Maybe that is causing the issue. I'll try that out.

@jack-geronimo, did you try to invalidate the caches in IntelliJ? The dependency index will be built from scratch so maybe this will solve the problem.

Sorry for the inconvenience!

**Comment by jack-geronimo** [comment]
> Hi guys, thanks a lot for sharing your issues with the plugin. I'm happy you could fix the problem, @Michaelafuller!
> 
> I'm not quite sure but the problem seems to occur in multi module Maven projects only. I created a multi module project for testing purpose but the issue didn't show up.
> 
> Are you using a Maven parent POM module in your projects which is referenced from other modules? Maybe that is causing the issue. I'll try that out.
> 
> @jack-geronimo, did you try to invalidate the caches in IntelliJ? The dependency index will be built from scratch so maybe this will solve the problem.
> 
> Sorry for the inconvenience!

Hi @mwalter,
I have recently invalidated the caches in IntelliJ, and now I also get the message "no project dependency information found" in the old project, which was still working before the invalidation. Both of these projects are multi-module Maven projects that refer to the parent POM.

Thanks for your effort

**Comment by mwalter** [comment]
Hi all! Good news. I've found the issue and provided a patch. Please upgrade to the newest version of the plugin.

@jack-geronimo and @roy-ackermann:
Let me know if you still encounter this issue or not. If everything's fine for you now, I'll close this issue. Waiting for your feedback.
